name: Auto Deploy to CVM

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to CVM
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ vars.HOST }}
        username: ${{ vars.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ vars.PORT }}
        script: |
          cd /data/sync_web 
          git pull origin main
          ./restart.sh
